all:
	arm-linux-gcc -o mginit mginit2.c \
	-I/home/cyc/minigui/libminigui-1.3.3/arm-linux-build/include \
	-I/home/cyc/minigui/tslib/arm-linux-build/include \
	-L/home/cyc/minigui/libminigui-1.3.3/arm-linux-build/lib \
	-L/home/cyc/minigui/tslib/arm-linux-build/lib \
	-lmgext -lminigui -lts
